const servicios = [
    {id: 1, presio: 2000, icon: "bi bi-book-half", title: "Asesoría Legal",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 2, presio: 2000, icon: "bi bi-people-fill", title: "Asesoría",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 3, presio: 2000, icon: "bi bi-bar-chart", title: "Elaboración",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 4, presio: 2000, icon: "bi bi-bank", title: "Constitución de empresasl",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 5, presio: 2000, icon: "bi bi-cash-coin", title: "Compraventa",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 6, presio: 2000, icon: "bi bi-hammer", title: "Defensa",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 7, presio: 2000, icon: "bi bi-bookmark-plus-fill", title: "Registro de marcas",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    {id: 8, presio: 2000, icon: "bi bi-percent", title: "Ejecución de garantías",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."},
    // {id: 9, icon: "bi bi-book-half", title: "Asesoría Legal",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."}
]

export const getServisios = () => {
    return servicios;
}