const servicios = [
    {id: 1, presio: 2000, icon: "bi bi-building-fill", title: "Asuntos Empresariales",descripccionBrev: "Asesoramos integralmente a empresas en sus operaciones legales diarias, brindando soluciones estratégicas en materia societaria, comercial, contractual y regulatoria. Nuestro enfoque es prevenir contingencias legales y fomentar un entorno jurídico sólido para el desarrollo del negocio."},
    {id: 2, presio: 2000, icon: "bi bi-book", title: "Elaboracion de Minutas",descripccionBrev: "Redactamos minutas legales con precisión y claridad, ya sea para actos societarios (constitución, aumentos de capital, juntas de accionistas) o notariales, garantizando que cumplan con todos los requisitos legales y reflejen fielmente la voluntad de las partes involucradas."},
    {id: 3, presio: 2000, icon: "bi bi-journal-text", title: "Elaboracion de contratos",descripccionBrev: "Diseñamos y revisamos contratos personalizados que protegen los intereses de nuestros clientes. Abarcamos desde contratos civiles y comerciales hasta contratos laborales y de inversión, asegurando cláusulas sólidas, justas y legalmente válidas."},
    {id: 4, presio: 2000, icon: "bi bi-bank", title: "Asociaciones empresariales",descripccionBrev: "Brindamos asesoría en la formación, estructuración y gestión de asociaciones empresariales, alianzas estratégicas, joint ventures y consorcios, velando por un marco legal claro que potencie la colaboración y minimice riesgos legales entre partes."},
    {id: 5, presio: 2000, icon: "bi bi-bank2", title: "Deliitos contra la administracion Publica",descripccionBrev: "Defendemos y representamos a nuestros clientes en investigaciones y procesos relacionados con delitos como colusión, cohecho, peculado y malversación. Nuestra experiencia en derecho penal y procesal nos permite ofrecer una defensa técnica y estratégica."},
    {id: 6, presio: 2000, icon: "bi bi-building-fill", title: "Constitucion de empresas",descripccionBrev: "Acompañamos a emprendedores e inversionistas en todo el proceso de constitución legal de su empresa, desde la elección del tipo societario adecuado hasta la inscripción en registros públicos y la obtención de licencias y permisos necesarios."},
    {id: 7, presio: 2000, icon: "bi bi-buildings", title: "Asesorias de bienes raices",descripccionBrev: "Ofrecemos asesoría legal en la compra, venta, alquiler y administración de inmuebles, así como en la revisión de títulos de propiedad, saneamiento legal, litigios inmobiliarios y contratos de arrendamiento, protegiendo los intereses patrimoniales de nuestros clientes."},
    {id: 8, presio: 2000, icon: "bi bi-bar-chart-line", title: "Orientacion en inverciones",descripccionBrev: "Brindamos orientación legal y estratégica para inversiones nacionales e internacionales, incluyendo estudios de viabilidad legal, cumplimiento normativo y evaluación de riesgos, contribuyendo a una toma de decisiones informada y segura."},
    {id: 9, presio: 2000, icon: "bi bi-journal-bookmark-fill", title: "Constitucion de Asociaciones ONG",descripccionBrev: "Asistimos en la creación legal de asociaciones civiles y organizaciones no gubernamentales, asegurando el cumplimiento de la normativa vigente y la correcta redacción de estatutos, así como su inscripción ante las entidades correspondientes."},
    {id: 9, presio: 2000, icon: "bi bi-journal-medical", title: "Registro de marcas - indecopi",descripccionBrev: "Gestionamos el proceso completo de registro de marcas ante la autoridad competente, desde la búsqueda de antecedentes hasta la obtención del título de registro, protegiendo los activos intangibles y la identidad comercial de nuestros clientes."},
    {id: 9, presio: 2000, icon: "bi bi-router", title: "GPS Diferencial",descripccionBrev: "Alta precision en medicion topografica.Diseño resistente y ligero (solo 850g). Bateria de larga duracion (hasta 15 horas de uso continuo). Tecnologia GNSS avanzada, compatible con todas las constelaciones de satelites. Radio incorporada con alcance de hasta 8 km para macima cobertura. Carga rapida tipo-C, listo en solo 3 Horas."},
    // {id: 9, icon: "bi bi-book-half", title: "Asesoría Legal",descripccionBrev: "Nuestra empresa CORPORATIVO MLOPEZ S.A.C, es una persona jurídica de derecho privado, promotora del Estudio Jurídico « MLÓPEZ ABOGADOS – ASESORES & CONSULTORES » Cuyo objeto social, es la prestación de servicios de asesoría legal y defensa técnica material, en asuntos empresariales, comerciales, tributarios, laborales."}
]

export const getServisios = () => {
    return servicios;
}